name: Modify Model/Test Case Template
description: Modify a model or a Test Case
title: "[Name/ID of the model/ test case to be improved]: "
labels: ["enhancement"]
projects: ["Colib0"]
assignees:
  - GJCRESYM
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!   
  - type: checkboxes
    attributes:
      label: Do you want to modify a model or test case?
      options:
        - label: Model
        - label: Test Case
    validations:
      required: true      
  - type: input
    id: Name
    attributes:
      label: Name the model/ test case ID you would like to modify 
      placeholder: ex. ID- 64
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: What is the impact of modification to the model or test case?
      options:
        - label: minor
        - label: moderate
        - label: major
    validations:
      required: true
  - type: textarea
    id: Expected-Behaviour
    attributes:
      label: Briefly describe the modification to the model/ test case
      placeholder: Tell us what you see!
      value: |
        Explain the purpose of the modification.

        Please upload your models/ test case template:
    validations:
      required: true


